//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentParamtersTb
    {
        public int EquipmentParameterId { get; set; }
        public int EquipmentTypeId { get; set; }
        public Nullable<int> AverageLifeTime { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
    }
}
